stages:
  - publish builder
  - publish to gitlab registry normal
  - publish to gitlab registry dev

variables:
  REGISTRY: "registry.gitlab.com/cyberos/infrastructure"

.docker-login: &docker-login
  variables:
    GIT_STRATEGY: clone
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  image: docker:stable
  except:
    - schedules
  services:
    - docker:dind
  before_script:
    - echo "${GITLAB_PASS}" | docker login registry.gitlab.com -u "${GITLAB_USER}" --password-stdin

publish-nomral:
  stage: publish to gitlab registry normal
  image: docker:stable
  variables:
    GIT_STRATEGY: clone
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  only:
    refs:
      - master
      - develop
  services:
    - docker:dind
  except:
    - schedules
  <<: *docker-login
  script:
    - docker build -f Docker/Dockerfile -t daobet --build-arg registry=${REGISTRY} .
    - docker tag daobet ${REGISTRY}/daobet:${CI_COMMIT_SHA:0:8}
    - docker tag daobet ${REGISTRY}/daobet:${CI_COMMIT_REF_NAME}-latest
    - docker tag daobet ${REGISTRY}/daobet:latest
    - docker push ${REGISTRY}/daobet

publish-dev:
  stage: publish to gitlab registry dev
  image: docker:stable
  variables:
    GIT_STRATEGY: clone
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  only:
    refs:
      - master
      - develop
  services:
    - docker:dind
  except:
    - schedules
  <<: *docker-login
  script:
    - docker build -f Docker/dev/Dockerfile -t daobet-dev --build-arg registry=${REGISTRY} .
    - docker tag daobet-dev ${REGISTRY}/daobet-dev:${CI_COMMIT_SHA:0:8}
    - docker tag daobet-dev ${REGISTRY}/daobet-dev:${CI_COMMIT_REF_NAME}-latest
    - docker tag daobet-dev ${REGISTRY}/daobet-dev:latest
    - docker push ${REGISTRY}/daobet-dev

publish-builder:
  stage: publish builder
  image: docker:stable
  variables:
    GIT_STRATEGY: clone
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  only:
    refs:
      - develop
      - master
    changes:
      - Docker/builder/Dockerfile
  services:
    - docker:dind
  except:
    - schedules
  <<: *docker-login
  script:
    - cd Docker/builder
    - docker build -t daobet-builder .
    - docker tag daobet-builder ${REGISTRY}/daobet-builder:${CI_COMMIT_SHA:0:8}
    - docker tag daobet-builder ${REGISTRY}/daobet-builder:${CI_COMMIT_REF_NAME}-latest
    - docker tag daobet-builder ${REGISTRY}/daobet-builder:latest
    - docker push ${REGISTRY}/daobet-builder
