language: minimal

git:
  depth: false

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

cache:
  directories:
    - $HOME/.ccache
  timeout: 1000

before_script:
  - docker pull daocasino/daobet-build-tools-"$DISTRO"
  - docker tag daocasino/daobet-build-tools-"$DISTRO" daobet-build-tools-"$DISTRO"
  - |
    if [[ "$TRAVIS_BRANCH" =~ ^debug- ]]; then
      BUILD_TYPE="Debug"
    else
      BUILD_TYPE="RelWithDebInfo"
    fi
  - |
    if [[ "$BUILD_TYPE" != Debug ]]; then
      if [[ "$TRAVIS_PULL_REQUEST" == false ]]; then
        TESTS="simulator|unit_test_wabt"
      else
        TESTS="simulator|unit_test_wabt|nodeos_sanity|nodeos_run"
      fi
    fi

script:
  - ./cicd/run build -d "$DISTRO" -p --build-type="${BUILD_TYPE}" --tests="$TESTS" --timeout=2400 daobet
  - |
    if [[ "$DISTRO" == ubuntu ]]; then
      ./cicd/run build -d "$DISTRO" -i daocasino/daobet:"$TRAVIS_BRANCH" daobet
      docker push daocasino/daobet:"$TRAVIS_BRANCH"
      if [[ "$TRAVIS_BRANCH" == master ]]; then
        docker tag daocasino/daobet:master daocasino/daobet:latest
        docker push daocasino/daobet:latest
      fi
    fi

deploy:
  provider: releases
  api_key:
    secure: "RF1x7wC+9wEFNwOVnuTYtKDdaPSRtKlPHZxuz7RkmJK6kpYcB42cBuRjX7eceW350GKNUcd0lD4Me9iyy2KBMhtsLJVDjjhRg4StyQJ9Iyn/CteY4bFWwq6WtW1KTpbs1y6fS68rgm25XWJlyZ6fdm99/hZ1XFkE1bFuaEYIoDyVJzeVgvn8iRrUONzRCzz5g3UbE8RJPkbcfnunSdbeIowZVPJMtnN9GVuvKFLyJT+g8p+nuVC/g0xhepWh5bMSXdoHrRai1rm0nZ2i23m+DYKfU8EZfl29Imc7qfWKAtXmWatwKsXtX6aWFaTYyKEIBJqCVrjet1f23EvcSa4LfgusRtTs+7miCTX0VxYDzRY4/ggr6/Xlr7dS46Yg7v99djW8Xrue/2tYARXWTwRXbDT/AiewWFLHaaodNIJidjSo+sMew1pXQRTs7Th3a4YACAWV90W2joS606LhbVhuAP3VDlN1nObsI8Tz8is1TNUD8/Sq8CxZg1uhQZkN8zKyRHlsrxddxW/rxeh+RUSQPOaF/ZsRaqrPoIAripw0harzWFJP+Zyy+sTTVVcovkPHrYji9TpKZ2p7I7Td9BVULdQyg5bhVXWpROlaDFV+/KzT/bjiVMSx9nsSp2IH9SkDB2Q4fHe8fJNMIqO+GHzOno+vF11cKj1aOkSqa4WVcbQ="
  file_glob: true
  file: build/pkgs/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

env:
  matrix:
    - "DISTRO=ubuntu"
    - "DISTRO=centos"

